workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    auth:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Auth-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/auth
    flows:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Flows-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/flows
    ledger:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Ledger-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/ledger
    payments:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Payments-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/payments
    reconciliation:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Reconciliation-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/reconciliation
    wallets:
        inputs:
            - location: ./formance-api-def/tsp-output/@typespec/openapi3/Wallets-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/wallets
targets: {}
