name: Build OpenAPI

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Formance API standards
        run: pnpm run build
        working-directory: formance-api-std
      
      - name: Build OpenAPI
        run: pnpm run build
        working-directory: formance-api-def

      # Upload the generated tsp-output directory as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsp-output
          path: formance-api-def/tsp-output